Update

diff --git a/rootfs/etc/s6-overlay/s6-rc.d/otbr-agent/run b/rootfs/etc/s6-overlay/s6-rc.d/otbr-agent/run
--- a/rootfs/etc/s6-overlay/s6-rc.d/otbr-agent/run
+++ b/rootfs/etc/s6-overlay/s6-rc.d/otbr-agent/run
@@ -17,20 +17,20 @@ declare otbr_rest_listen_port
 backbone_if=$BACKBONE_IF
 device=$DEVICE
 
-if -z ${network_device}; then
-    device="/tmp/ttyOTBR"
-fi
+# if ! -z ${network_device}; then
+#     device="/tmp/ttyOTBR"
+# fi
 
-baudrate=$(bashio::config 'baudrate')
+baudrate=$BAUDRATE
 flow_control=""
 
-if bashio::config.true 'flow_control'; then
-    flow_control="&uart-flow-control"
-else
+if [ "$FLOW_CONTROL" == "0" ]; then
     flow_control="&uart-init-deassert"
+else
+    flow_control="&uart-flow-control"
 fi
 
-otbr_log_level=$(bashio::string.lower "$(bashio::config otbr_log_level)")
+otbr_log_level=${OTBR_LOG_LEVEL:-info}
 case "${otbr_log_level}" in
     debug)
         otbr_log_level_int="7"
@@ -57,16 +57,17 @@ case "${otbr_log_level}" in
         otbr_log_level_int="0"
         ;;
     *)
-        bashio::exit.nok "Unknown otbr_log_level: ${otbr_log_level}"
+        log 'info' "Unknown otbr_log_level: ${otbr_log_level}"
+        otbr_log_level_int="6"
         ;;
 esac
 
 if [ -z ${backbone_if} ]; then
-    bashio::log.warning "No primary network interface found! Using static eth0."
+    log 'warning' "No primary network interface found! Using static eth0."
     backbone_if="eth0"
 fi
 
-mkdir -p /data/thread && ln -sft /var/lib /data/thread || bashio::exit.nok "Could not create directory /var/lib/thread to store Thread data."
+mkdir -p /data/thread && ln -sft /var/lib /data/thread || echo "Could not create directory /var/lib/thread to store Thread data."
 
 # We compile the OTBR with firewall support, so otbr-agent tries to update the
 # ipsets. Therefor, create ipsets always to avoid errors from otbr-agent. Just
@@ -76,7 +77,7 @@ ipset create -exist otbr-ingress-deny-src-swap hash:net family inet6
 ipset create -exist otbr-ingress-allow-dst hash:net family inet6
 ipset create -exist otbr-ingress-allow-dst-swap hash:net family inet6
 
-if bashio::config.true 'firewall'; then
+if [ "$FIREWALL" != "0" ] ; then
     log 'info'  "Setup OTBR firewall..."
     ip6tables -N $otbr_forward_ingress_chain
     ip6tables -I FORWARD 1 -o $thread_if -j $otbr_forward_ingress_chain
@@ -97,7 +98,7 @@ else
     ip6tables-legacy -P FORWARD ACCEPT
 fi
 
-if bashio::config.true 'nat64'; then
+if [ "$NAT64" != "0" ] ; then
     iptables -t mangle -A PREROUTING -i ${thread_if} -j MARK --set-mark 0x1001
     iptables -t nat -A POSTROUTING -m mark --mark 0x1001 -j MASQUERADE
     iptables -t filter -A FORWARD -o ${backbone_if} -j ACCEPT
@@ -105,16 +106,7 @@ if bashio::config.true 'nat64'; then
 fi
 
 otbr_rest_listen="::"
-otbr_rest_listen_port="$(bashio::addon.port 8081)"
-
-# If user port is not set, listen on local interface only
-if ! bashio::var.has_value "${otbr_rest_listen_port}"; then
-    otbr_rest_listen="$(bashio::addon.ip_address)"
-    otbr_rest_listen_port="8081"
-elif [ "${otbr_rest_listen_port}" != "8081" ]; then
-    bashio::log.warning "Custom OpenThread REST API port is not supported. Using 8081."
-    otbr_rest_listen_port="8081"
-fi
+otbr_rest_listen_port="${OTBR_REST_PORT:-8081}"
 
 # Store REST API listen information for check script
 echo "${otbr_rest_listen}" > /tmp/otbr-agent-rest-api
